# FOR DEVELOPMENT ONLY.

version: '3'

services:
  postgres:
    container_name: postgres-dev
    image: postgres:latest
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}


volumes:
  pg-data-dev:
