# FOR DEVELOPMENT ONLY.

version: '3'

services:
  redis:
    container_name: redis-dev
    image: bitnami/redis:latest
    env_file:
      - .env
    volumes:
      - redis-data-dev:/bitnami/redis/data
    ports:
      - '${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}'

  postgres:
    container_name: postgres-dev
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  pgadmin:
    container_name: pgadmin-dev
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    volumes:
      - pgadmin-data-dev:/var/lib/pgadmin
    ports:
      - '5050:80'

volumes:
  redis-data-dev:
  pg-data-dev:
  pgadmin-data-dev:
